### ISSUE TITLE
@Scheduled annotation in non-singletons 

### ISSUE THREAD

**Issue by zalizko** [xpoft/spring-vaadin#14]
Hi,
did u tested spring scheduling with all scopes?

Maybe problem not in your plugin, but in my application scheduling works only in prototype scoped bean ... if I set (as needed) session scope - scheduling does not working. In Spring documentation I did not found any requirements related to scope in scheduling context.

``` java
@Configuration
@ComponentScan(basePackageClasses = ApplicationConfig.class)
@EnableScheduling
public class ApplicationConfig {
    ...
}

@Component
@Scope("session")
public class ProjectsPanel extends Panel {
    ...
    @Scheduled(fixedDelay = 1000)
    public void refresher() {
        LOGGER.debug(" -- task --");
    }
}
```

**Comment by arshabh** [comment]
Was anyone able to schedule in prototype scoped bean?
